/**
 * Fault types.
 */
const StandardFaultType = {
    NO_START: 'NO_START',
    NO_END: 'NO_END',
    IMPLICIT_START: 'IMPLICIT_START',
    IMPLICIT_END: 'IMPLICIT_END',
    NON_GATEWAY_MULTIPLE_IN: 'NON_GATEWAY_MULTIPLE_IN',
    NON_GATEWAY_MULTIPLE_OUT: 'NON_GATEWAY_MULTIPLE_OUT',
    NON_INTERRUPTING_BACK: 'NON_INTERRUPTING_BACK',
    GATEWAY_WITHOUT_MULTIPLE_FLOWS: 'GATEWAY_WITHOUT_MULTIPLE_FLOWS',
    LOOP_EXIT_NOT_XOR: 'LOOP_EXIT_NOT_XOR',
    LOOP_ENTRY_IS_AND: 'LOOP_ENTRY_IS_AND',
    LOOP_BACK_JOIN_IS_AND: 'LOOP_BACK_JOIN_IS_AND',
    POTENTIAL_DEADLOCK: 'POTENTIAL_DEADLOCK',
    POTENTIAL_LACK_OF_SYNCHRONIZATION: 'POTENTIAL_LACK_OF_SYNCHRONIZATION',
    POTENTIAL_ENDLESS_LOOP: 'POTENTIAL_ENDLESS_LOOP',
    LIVE_LOCK: 'LIVE_LOCK',
    DEAD_LOOP: 'DEAD_LOOP'
};

export { StandardFaultType };